# Generated by Django 2.2.2 on 2019-06-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("atlas", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="profile", name="handle", field=models.TextField(null=True)
        )
    ]
