# Generated by Django 2.2.2 on 2019-07-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("atlas", "0002_profile_handle")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="primary_phone",
            field=models.TextField(null=True),
        )
    ]
