# Generated by Django 2.1.4 on 2019-06-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [(" atlas" "0003_identity_is_active")]

    operations = [
        migrations.AddField(
            model_name="profile", name="department", field=models.TextField(null=True)
        )
    ]
