# Generated by Django 2.2.2 on 2019-07-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("atlas", "0003_profile_primary_phone")]

    operations = [
        migrations.AddField(
            model_name="office",
            name="lat",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="office",
            name="lng",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
