# Generated by Django 2.2.2 on 2019-07-16 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("atlas", "0004_auto_20190711_1346")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_human",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="office",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles",
                to="atlas.Office",
            ),
        ),
    ]
