# Generated by Django 2.2.2 on 2019-06-08 19:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("atlas", "0007_auto_20190605_0528")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="config",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        )
    ]
