# Generated by Django 2.2.2 on 2019-07-17 21:13

from django.db import migrations


def backfill_external_ids(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Office = apps.get_model("atlas", "Office")
    for office in Office.objects.filter(external_id__isnull=True):
        office.external_id = office.name
        office.save()


class Migration(migrations.Migration):

    dependencies = [("atlas", "0007_office_external_id")]

    operations = [migrations.RunPython(backfill_external_ids)]
