# Generated by Django 2.2.2 on 2019-07-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("atlas", "0008_auto_20190717_2113")]

    operations = [
        migrations.AlterField(
            model_name="office",
            name="external_id",
            field=models.CharField(max_length=64, unique=True),
        )
    ]
