# Generated by Django 2.2.2 on 2019-07-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("atlas", "0009_auto_20190717_2114")]

    operations = [
        migrations.AlterField(
            model_name="office", name="name", field=models.CharField(max_length=64)
        )
    ]
