# Generated by Django 2.2.2 on 2019-07-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("atlas", "0010_auto_20190717_2229")]

    operations = [
        migrations.AddField(
            model_name="office",
            name="region_code",
            field=models.CharField(max_length=64, null=True),
        )
    ]
