# Generated by Django 2.2.2 on 2019-07-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("atlas", "0011_office_region_code")]

    operations = [
        migrations.AddField(
            model_name="office", name="description", field=models.TextField(null=True)
        ),
        migrations.AddField(
            model_name="office",
            name="postal_code",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
