# Generated by Django 2.2.2 on 2019-07-17 23:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("atlas", "0012_auto_20190717_2233")]

    operations = [
        migrations.AddField(
            model_name="identity",
            name="scopes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32), default=list, size=None
            ),
        )
    ]
