# Generated by Django 2.2.2 on 2019-07-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("atlas", "0013_identity_scopes")]

    operations = [
        migrations.AddField(
            model_name="office",
            name="administrative_area",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="office",
            name="locality",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
