# Generated by Django 2.2.2 on 2019-07-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("atlas", "0015_profile_pronouns")]

    operations = [
        migrations.AddField(
            model_name="profile", name="bio", field=models.TextField(null=True)
        ),
        migrations.AddField(
            model_name="profile", name="github", field=models.TextField(null=True)
        ),
        migrations.AddField(
            model_name="profile", name="linkedin", field=models.TextField(null=True)
        ),
        migrations.AddField(
            model_name="profile", name="twitter", field=models.TextField(null=True)
        ),
    ]
