# Generated by Django 2.2.2 on 2019-07-29 17:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("atlas", "0017_auto_20190724_0111")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_contractor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="schedule",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=6), null=True, size=7
            ),
        ),
    ]
