# Generated by Django 2.2.2 on 2019-07-29 19:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("atlas", "0018_auto_20190729_1735")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="schedule",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=8), null=True, size=7
            ),
        )
    ]
