# Generated by Django 2.2.2 on 2019-08-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("atlas", "0019_auto_20190729_1915")]

    operations = [
        migrations.RemoveField(model_name="profile", name="is_contractor"),
        migrations.AddField(
            model_name="profile",
            name="employee_type",
            field=models.TextField(null=True),
        ),
    ]
