# Generated by Django 2.2.4 on 2019-08-13 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("atlas", "0020_auto_20190806_2344")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="referred_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
