# Generated by Django 2.2.5 on 2019-09-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("atlas", "0021_profile_referred_by")]

    operations = [
        migrations.AddField(
            model_name="profile", name="team", field=models.TextField(null=True)
        )
    ]
