# Generated by Django 2.2.5 on 2019-09-25 22:23

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


def backfill_departments(apps, schema_editor):
    Profile = apps.get_model("atlas", "Profile")
    Department = apps.get_model("atlas", "Department")

    cache = {}
    for profile in Profile.objects.filter(department__isnull=False).exclude(
        department=""
    ):
        if profile.department in cache:
            department = cache[profile.department]
        else:
            department = Department.objects.get_or_create(name=profile.department)[0]
            cache[department.name] = department.id
        profile.department = cache[profile.department]
        profile.save()


class Migration(migrations.Migration):

    dependencies = [("atlas", "0022_profile_team")]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tree",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(),
                        db_index=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="atlas.Department",
                    ),
                ),
            ],
            options={"db_table": "department", "unique_together": {("parent", "name")}},
        ),
        migrations.RunPython(backfill_departments),
        migrations.RemoveField(model_name="profile", name="team"),
        migrations.AlterField(
            model_name="profile",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="atlas.Department",
            ),
        ),
    ]
