# Generated by Django 2.2.5 on 2019-10-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("atlas", "0023_auto_20190925_2223")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="has_onboarded",
            field=models.BooleanField(default=False),
        )
    ]
