# Generated by Django 2.2.5 on 2019-10-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("atlas", "0024_profile_has_onboarded")]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        )
    ]
