# Generated by Django 2.2.5 on 2019-10-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("atlas", "0025_auto_20191015_1957")]

    operations = [
        migrations.AddField(
            model_name="department",
            name="cost_center",
            field=models.PositiveIntegerField(null=True, unique=True),
        )
    ]
