# Generated by Django 2.2.5 on 2020-05-19 17:46

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("atlas", "0027_profile_is_directory_hidden")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles",
                to="atlas.Department",
            ),
        ),
        migrations.CreateModel(
            name="Change",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "object_type",
                    models.CharField(
                        choices=[("user", "user"), ("office", "office")], max_length=32
                    ),
                ),
                ("object_id", models.UUIDField()),
                ("changes", django.contrib.postgres.fields.jsonb.JSONField()),
                ("version", models.PositiveIntegerField()),
            ],
            options={"unique_together": {("object_type", "object_id", "version")}},
        ),
    ]
