# Generated by Django 2.2.5 on 2020-05-19 21:46

import atlas.models.change
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("atlas", "0029_change_user")]

    operations = [
        migrations.AddField(
            model_name="change",
            name="previous",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                encoder=atlas.models.change.CustomJSONEncoder, null=True
            ),
        ),
        migrations.AlterField(
            model_name="change",
            name="changes",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                encoder=atlas.models.change.CustomJSONEncoder
            ),
        ),
        migrations.AlterField(
            model_name="change",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("user", "user"),
                    ("office", "office"),
                    ("department", "department"),
                ],
                max_length=32,
            ),
        ),
    ]
