steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
    '-c',
    'docker pull us.gcr.io/$PROJECT_ID/$atlas-backend:latest || true',
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--cache-from', 'us.gcr.io/$PROJECT_ID/atlas-frontend:latest',
    '--build-arg', 'BUILD_REVISION=$COMMIT_SHA',
    '--build-arg', 'SENTRY_DSN=$SENTRY_DSN',
    '--build-arg', 'GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID',
    '--build-arg', 'GOOGLE_MAPS_KEY=$GOOGLE_MAPS_KEY',
    '--build-arg', 'GOOGLE_REDIRECT_URI=$GOOGLE_REDIRECT_URI',
    '--build-arg', 'GOOGLE_DOMAIN=$GOOGLE_DOMAIN',
    '--build-arg', 'API_ENDPOINT=$API_ENDPOINT',
    '-t', 'us.gcr.io/$PROJECT_ID/atlas-frontend:$COMMIT_SHA',
    '-t', 'us.gcr.io/$PROJECT_ID/atlas-frontend:latest',
    '.'
  ]
images:
- 'us.gcr.io/$PROJECT_ID/atlas-frontend:$COMMIT_SHA'
- 'us.gcr.io/$PROJECT_ID/atlas-frontend:latest'
