# sentry:
#   organization: sentry
#   project: atlas
#   repository: getsentry/atlas

steps:
  - kind: KubernetesDeployment
    selector:
      label_selector: service=atlas
    containers:
      - image: us.gcr.io/internal-sentry/atlas-frontend:{sha}
        name: frontend
      - image: us.gcr.io/internal-sentry/atlas-backend:{sha}
        name: backend
      - image: us.gcr.io/internal-sentry/atlas-backend:{sha}
        name: worker
