language: python
sudo: true
dist: xenial
services:
  - postgresql
python:
  - "3.7"
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
env:
  global:
    - NODE_ENV=production
    - PIP_DISABLE_PIP_VERSION_CHECK=on
install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/0.12.16/get-poetry.py | python
  - curl -sSLf https://get.volta.sh | bash
  - PATH=$HOME/.poetry/bin:$PATH NODE_ENV= make
script:
  - git --version
  - PATH=$HOME/.poetry/bin:$PATH PATH=node_modules/.bin:$PATH pre-commit run -a -v
  - PATH=$HOME/.poetry/bin:$PATH poetry run py.test -v --cov . --cov-report="xml:.artifacts/coverage.xml" --junit-xml=".artifacts/pytest.junit.xml"
