steps:
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        for d in */; do
          config="${d}cloudbuild.yaml"
          if [[ ! -f "${config}" ]]; then
            continue
          fi

          echo "Building $d ... "
          (
            gcloud builds submit $d --substitutions=COMMIT_SHA=$COMMIT_SHA --config=${config}
          ) &
        done
        wait
images:
  - "gcr.io/$PROJECT_ID/atlas-backend:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/atlas-backend:latest"
  - "gcr.io/$PROJECT_ID/atlas-frontend:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/atlas-frontend:latest"
