steps:
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-ceu"
      - |
        for d in */; do
          config="${d}cloudbuild.yaml"
          if [[ ! -f "${config}" ]]; then
            echo "No cloudbuild.yaml found in $d"
            continue
          fi

          echo "Building $d ... "
          (
            gcloud builds submit $d --substitutions=COMMIT_SHA=$COMMIT_SHA --config=${config}
          )
        done
        wait
logsBucket: "gs://sentryio-cloudbuild-logs/getsentry/"
