version: "3.7"

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  # web:
  #   build: .
  #   command: python /usr/src/atlas/bin/atlas runserver 0.0.0.0:8000
  #   volumes:
  #     - .:/usr/src/atlas
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - db

volumes:
  postgres_data:
