version: "3.7"

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  redis:
    image: redis:5.0-alpine
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
  # frontend:
  #   build: frontend
  #   # command: npm dev
  #   # volumes:
  #   #   - frontend:/usr/src/app/frontend
  #   ports:
  #     - 3000:3000
  # backend:
  #   build: backend
  #   # command: python /usr/src/app/bin/atlas runserver 0.0.0.0:8000
  #   # volumes:
  #   #   - backend:/usr/src/app/backend
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - db

volumes:
  postgres_data:
  redis_data:
