steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker pull us.gcr.io/$PROJECT_ID/$atlas-backend:latest || true"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--cache-from",
        "us.gcr.io/$PROJECT_ID/atlas-backend:latest",
        "--build-arg",
        "BUILD_REVISION=$COMMIT_SHA",
        "-t",
        "us.gcr.io/$PROJECT_ID/atlas-backend:$COMMIT_SHA",
        "-t",
        "us.gcr.io/$PROJECT_ID/atlas-backend:latest",
        ".",
      ]
images:
  - "us.gcr.io/$PROJECT_ID/atlas-backend:$COMMIT_SHA"
  - "us.gcr.io/$PROJECT_ID/atlas-backend:latest"
options:
  substitution_option: "ALLOW_LOOSE"
logsBucket: "gs://sentryio-cloudbuild-logs/getsentry/"
