# Generated by Django 2.1.4 on 2019-06-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("backend", "0004_profile_department")]

    operations = [
        migrations.AddField(
            model_name="identity",
            name="is_admin",
            field=models.BooleanField(default=False),
        )
    ]
