# Generated by Django 2.1.4 on 2019-06-05 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("backend", "0006_auto_20190604_1904")]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="joined_at", new_name="date_started"
        )
    ]
