name: Atlas

on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      postgresql:
        image: postgres:10.1-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:5.0-alpine
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        env:
          POETRY_VERSION: 1.1.4
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit==2.20 poetry==1.2.0
          curl -sSLf https://get.volta.sh | bash
          NODE_ENV= make
      - name: Lint with pre-commit
        run: |
          PATH=node_modules/.bin:$PATH pre-commit run -a -v
      - name: Test backend
        env:
          CELERY_BROKER_URL: redis://localhost:6379/0
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
          SENTRY_ENVIRONMENT: test
        run: |
          cd backend && poetry run pytest -v --cov . --cov-report="xml:.artifacts/coverage.xml" --junit-xml=".artifacts/pytest.junit.xml"
      - name: Test frontend
        env:
          SENTRY_ENVIRONMENT: test
        run: |
          npm test
